### PR TITLE
WIP serial comms library updates

### PR DESCRIPTION
**Pull request by networkfusion**
## Description
This pull request adds solutions and projects.

It also implements some of the functions in DataReader and DataWriter.

### CODE REVIEW

**Comment by josesimoes** [comment]
@networkfusion there seems to be some conflicting files...
(are you sure that you are branching from wip-Windows.Devices.SerialCommunication?)

**Comment by networkfusion** [comment]
It is based off the original commit (same PR branch) so I am not sure what is going on there (I don't want to have to start messing about with new forks)... anyway it is fine for this PR to be a ref to my branch until more progress is made I guess, unless someone else wants to work on it as well...

**Comment by josesimoes** [comment]
I think you probably have to rebase it from the new branch nanoframework:wip-Windows.Devices.SerialCommunication.
Or, as an alternative, branch from the master: wip-Windows.Devices.SerialCommunication and start working on top of that one.
As it is the merge can't be done as you can see bellow.

**Comment by networkfusion** [comment]
Replaced with #178

**Pull request closed without merging**
