### PR TITLE
Added new libraries

### PR DESCRIPTION
**Pull request by networkfusion**
## Description
Added Skeletons of :
ADC
PWM
SerialCommunication

## Motivation and Context
This will make it easier for implementation and includes code documentation. Async providers have been replaced with non async calls.

## How Has This Been Tested? (if applicable)
Not tested Yet (as there is no implementation.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by josesimoes** [comment]
@networkfusion  could you please sign the CLA above 😉 ?

**Comment by josesimoes** [comment]
Would it be too much trouble splitting this in 3 separate PRs so we can mange them independently?

**Comment by networkfusion** [comment]
Thought I had already done it... must have been for nf-interpreter... (why do we have the same (but separate) CLA for each project???

I will split these out, but not on the native side...

**Comment by josesimoes** [comment]
> (why do we have the same (but separate) CLA for each project???

This is how it's currently handled by the CLA manager: one agreement for each repo. 
There are repos that don't require a CLA (community targets, ChibiOS, Home, wiki, GitHub pages, etc) so we have to have this handled separately.

**Comment by josesimoes** [comment]
Replaced by #168, #169 and #170.

**Pull request closed without merging**
